# Generated by Django 3.2 on 2023-05-18 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название тега', max_length=200, verbose_name='Название')),
                ('color', models.CharField(blank=True, help_text='Введите текст для тега', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Обозначение цвета должно состоять из знака #  и 6 символов (заглавные буквы/цифры) после!', regex='^#[A-Z0-9_]{6}$')], verbose_name='Цвет виджета тега')),
                ('slug', models.CharField(help_text='Введите слаг для тега', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Слаг может состоять только из цифр/букв и знака "_"!', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
