# Generated by Django 3.2 on 2023-05-26 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20230525_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#100100', help_text='Введите текст для тега', max_length=7, validators=[django.core.validators.RegexValidator(message='Обозначение цвета должно состоять из знака #  и 6 символов (заглавные буквы/цифры) после!', regex='^#[A-Z0-9_]{6}$')], verbose_name='Цвет виджета тега'),
            preserve_default=False,
        ),
    ]
