# Generated by Django 3.2 on 2023-05-26 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, help_text='Выберите количество ингредиента', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
