# Generated by Django 3.2 on 2023-05-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipe_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
