# Generated by Django 3.2 on 2023-05-28 05:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20230527_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='Выберите цвет для тега', image_field=None, max_length=18, samples=None, verbose_name='Цвет виджета тега'),
        ),
    ]
