# Generated by Django 3.2 on 2023-05-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20230528_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='_ingredients',
        ),
    ]
