# Generated by Django 3.2 on 2023-05-27 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230527_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Введите ваше имя', max_length=150, validators=[django.core.validators.RegexValidator(message='Значение имени должно содержать только буквы!', regex='[А-Яа-яA-Za-z]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Введите вашу фамилию', max_length=150, validators=[django.core.validators.RegexValidator(message='Значение фамилии должно содержать только буквы!', regex='[А-Яа-яA-Za-z]+$')], verbose_name='Фамилия'),
        ),
    ]
